// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/infobloxopen/acme/pkg/pb/service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/infobloxopen/acme/pkg/pb/service.proto

It has these top-level messages:
	VersionResponse
	PublishResponse
	PublishRequest
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Example Publish Response
type PublishResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *PublishResponse) Reset()                    { *m = PublishResponse{} }
func (m *PublishResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()               {}
func (*PublishResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PublishResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// Example Publish Request
type PublishRequest struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PublishRequest) Reset()                    { *m = PublishRequest{} }
func (m *PublishRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()               {}
func (*PublishRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PublishRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
	proto.RegisterType((*PublishResponse)(nil), "service.PublishResponse")
	proto.RegisterType((*PublishRequest)(nil), "service.PublishRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Acme service

type AcmeClient interface {
	GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	// Example Publish call
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type acmeClient struct {
	cc *grpc.ClientConn
}

func NewAcmeClient(cc *grpc.ClientConn) AcmeClient {
	return &acmeClient{cc}
}

func (c *acmeClient) GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/service.Acme/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acmeClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := grpc.Invoke(ctx, "/service.Acme/Publish", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Acme service

type AcmeServer interface {
	GetVersion(context.Context, *google_protobuf.Empty) (*VersionResponse, error)
	// Example Publish call
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
}

func RegisterAcmeServer(s *grpc.Server, srv AcmeServer) {
	s.RegisterService(&_Acme_serviceDesc, srv)
}

func _Acme_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcmeServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Acme/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcmeServer).GetVersion(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acme_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcmeServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Acme/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcmeServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Acme_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Acme",
	HandlerType: (*AcmeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _Acme_GetVersion_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _Acme_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/infobloxopen/acme/pkg/pb/service.proto",
}

func init() { proto.RegisterFile("github.com/infobloxopen/acme/pkg/pb/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x25, 0x08, 0xb5, 0x60, 0x09, 0x2a, 0x05, 0xa9, 0x54, 0x85, 0x01, 0x65, 0x40, 0xa5, 0xd0,
	0x58, 0xc0, 0xd6, 0x2e, 0x80, 0x84, 0x58, 0xa1, 0x03, 0x03, 0x9b, 0x1d, 0xae, 0xae, 0x45, 0xe2,
	0x33, 0xb1, 0x53, 0xe8, 0xca, 0x2f, 0x30, 0xf2, 0x59, 0xfc, 0x02, 0x1f, 0x82, 0x9a, 0x38, 0x51,
	0x28, 0x20, 0xb1, 0xe5, 0xdd, 0xbd, 0x7b, 0xf7, 0xee, 0xc5, 0xe4, 0x44, 0x48, 0x3b, 0xcd, 0x78,
	0x18, 0x61, 0x42, 0xa5, 0x9a, 0x20, 0x8f, 0xf1, 0x05, 0x35, 0x28, 0xca, 0xa2, 0x04, 0xa8, 0x7e,
	0x14, 0x54, 0x73, 0x6a, 0x20, 0x9d, 0xc9, 0x08, 0x42, 0x9d, 0xa2, 0x45, 0xbf, 0xe9, 0x60, 0x77,
	0x57, 0x20, 0x8a, 0x18, 0x68, 0x5e, 0xe6, 0xd9, 0x84, 0x42, 0xa2, 0xed, 0xbc, 0x60, 0x75, 0xf7,
	0x5c, 0x93, 0x69, 0x49, 0x99, 0x52, 0x68, 0x99, 0x95, 0xa8, 0x8c, 0xeb, 0x8e, 0x6a, 0x6b, 0xe3,
	0xf9, 0xc4, 0x16, 0x1a, 0xd1, 0x40, 0x80, 0x1a, 0xcc, 0x58, 0x2c, 0x1f, 0x98, 0x05, 0xfa, 0xe3,
	0xc3, 0x0d, 0x1f, 0xd7, 0xc8, 0xe6, 0x99, 0x09, 0x01, 0x29, 0x45, 0x9d, 0xcb, 0xff, 0xb2, 0x6a,
	0xf8, 0xd7, 0x85, 0x35, 0x15, 0x81, 0x69, 0x52, 0x49, 0x2c, 0x40, 0x31, 0x1b, 0x1c, 0x91, 0xd6,
	0x1d, 0xa4, 0x46, 0xa2, 0x1a, 0x83, 0xd1, 0xa8, 0x0c, 0xf8, 0x1d, 0xd2, 0x9c, 0x15, 0xa5, 0x8e,
	0xb7, 0xef, 0xf5, 0x36, 0xc6, 0x25, 0x0c, 0x0e, 0x49, 0xeb, 0x26, 0xe3, 0xb1, 0x34, 0xd3, 0x8a,
	0xdc, 0x26, 0x0d, 0x63, 0x99, 0xcd, 0x8c, 0xe3, 0x3a, 0x14, 0xf4, 0xc9, 0x56, 0x45, 0x7d, 0xca,
	0xc0, 0xd8, 0x85, 0x6c, 0x02, 0xc6, 0x30, 0x01, 0xa5, 0xac, 0x83, 0xa7, 0xef, 0x1e, 0x59, 0xbb,
	0x88, 0x12, 0xf0, 0xcf, 0x09, 0xb9, 0x06, 0xeb, 0xfc, 0xf8, 0xed, 0xb0, 0x08, 0x38, 0x2c, 0xd3,
	0x0f, 0xaf, 0x16, 0xe9, 0x77, 0x3b, 0x61, 0xf9, 0xb7, 0x96, 0x9c, 0x07, 0x2b, 0xfe, 0x2d, 0x69,
	0xba, 0xb5, 0xfe, 0x4e, 0x45, 0xfb, 0x6e, 0xa4, 0x36, 0xbf, 0x74, 0x4c, 0xb0, 0xfd, 0xfa, 0xf1,
	0xf9, 0xb6, 0xba, 0x19, 0xac, 0x53, 0x5d, 0x74, 0x86, 0x5e, 0xff, 0xb2, 0x77, 0x7f, 0xf0, 0x8f,
	0x17, 0x34, 0xd2, 0x9c, 0x37, 0x72, 0xa3, 0x67, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x00, 0xeb,
	0x2a, 0x5b, 0x72, 0x02, 0x00, 0x00,
}
